# Site settings
title: Katye McCullough Russell
email: kmr@katyerussell.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for junior web developer, Katye McCullough Russell
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katyerussell.com" # the base hostname & protocol for your site
twitter_username: complikatyed
github_username:  complikatyed

# Build settings
markdown: kramdown
